name: workout_app
description: Простое приложение для ведения тренировок на Flutter
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  intl: ^0.20.2
  shared_preferences: ^2.0.15
  firebase_core: ^2.23.0
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.15.3
  connectivity_plus: ^4.0.0

  digital_diary_app:
    path: ../digital_diary_app

  nutrition_tracker:
    path: ../nutrition_tracker

  finance_tracker:
    path: ../finance_tracker

  planner_app:
    path: ../planner_app

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

flutter:
  uses-material-design: true