// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8RLDnBKR7y_GHzlWAGtIwtKajx8UBKrA',
    appId: '1:700671083968:web:46c8fb48f87fa9c6eaf425',
    messagingSenderId: '700671083968',
    projectId: 'app1-50114',
    authDomain: 'app1-50114.firebaseapp.com',
    storageBucket: 'app1-50114.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVS7rq-bI9LzsoUel3m7rJPdl1cCuuN3I',
    appId: '1:700671083968:android:4e89f7bfb4962f06eaf425',
    messagingSenderId: '700671083968',
    projectId: 'app1-50114',
    storageBucket: 'app1-50114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiuGIDN7uFqM4GGEapCHYj0uNAXcLr9cE',
    appId: '1:700671083968:ios:39d57b88d1ae2dc5eaf425',
    messagingSenderId: '700671083968',
    projectId: 'app1-50114',
    storageBucket: 'app1-50114.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiuGIDN7uFqM4GGEapCHYj0uNAXcLr9cE',
    appId: '1:700671083968:ios:39d57b88d1ae2dc5eaf425',
    messagingSenderId: '700671083968',
    projectId: 'app1-50114',
    storageBucket: 'app1-50114.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8RLDnBKR7y_GHzlWAGtIwtKajx8UBKrA',
    appId: '1:700671083968:web:d3364696f1e5c7ebeaf425',
    messagingSenderId: '700671083968',
    projectId: 'app1-50114',
    authDomain: 'app1-50114.firebaseapp.com',
    storageBucket: 'app1-50114.firebasestorage.app',
  );
}
